name: Allure Report
run-name: ${{ github.actor }} is creating Allure report 🚀

on: workflow_dispatch

permissions:
  contents: write

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'zulu'

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set execute permissions for run_tests.sh
        run: chmod +x run_tests.sh

      - name: Run Test
        run: ./run_tests.sh
        continue-on-error: true

      - name: Install Allure CommandLine
        run: |
          curl -o allure-2.22.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.1/allure-commandline-2.22.1.tgz
          sudo tar -zxvf allure-2.22.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.22.1/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure Report
        run: sudo allure generate target/allure-results --clean -o allure-report

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 30

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
